package com.captionglass.engine

fun main() {
    val gate = SourceGate(maxWaitMs = 5_000)
    check(gate.update("I don't think he will", 0, 0).committed == null)
    val stable = gate.update("I don't think he will", 1, 500)
    check(stable.stable.isNotEmpty() && stable.committed == null)
    check(gate.update("I don't think he will come.", 2, 1_000).committed == null)
    val final = gate.update("I don't think he will come.", 3, 1_500, isFinal = true)
    check(final.committed == "I don't think he will come.")
    check(gate.update("I don't think he will come.", 3, 1_500, true).committed == null)

    val longSentence = SourceGate(maxWaitMs = 5_000)
    longSentence.update("We can keep going", 0, 0)
    check(longSentence.update("We can keep going", 1, 5_000).committed != null)
    check(longSentence.update("We cannot keep going", 2, 5_100).correctionRequired)
    check(!longSentence.update("We cannot keep going now", 3, 5_200).invalidatesCommitted)
    check(longSentence.update("We cannot keep going now.", 4, 5_500, true).committed == "We cannot keep going now.")
    check(longSentence.update("We cannot keep going now.", 5, 5_600, true).committed == null)
    val punctuation = SourceGate()
    punctuation.update("Dr. Smith paid 3.14 dollars", 0, 0)
    check(punctuation.update("Dr. Smith paid 3.14 dollars", 1, 500).committed == null)
    punctuation.update("Dr. Smith paid 3.14 dollars. Thank you", 2, 700)
    check(punctuation.update("Dr. Smith paid 3.14 dollars. Thank you", 3, 900).committed == "Dr. Smith paid 3.14 dollars.")
    check(punctuation.update("Dr. Smith paid 3.14 dollars. Thank you", 4, 1100, true).committed == "Thank you")
    val openTail = SourceGate()
    openTail.update("I don't think he will", 0, 0)
    check(openTail.update("I don't think he will", 1, 5500).committed == null)
    val latePunctuation = SourceGate(maxWaitMs = 1000)
    latePunctuation.update("The result is ready", 0, 0)
    check(latePunctuation.update("The result is ready", 1, 1000).committed == "The result is ready")
    check(latePunctuation.update("The result is ready.", 2, 1100, true).committed == null)
    val words = SourceGate()
    words.update("we can", 0, 0)
    check(words.update("we can't", 1, 500).stable == "we ")
    val chinese = SourceGate()
    chinese.update("这是原文", 0, 0)
    check(chinese.update("这是原文内容", 1, 500).stable == "这是原文")
    val pair = LanguagePair(Language.JA, Language.ZH)
    check(pair.swapped() == LanguagePair(Language.ZH, Language.JA))
    check(pair.withSource(Language.ZH) == pair.swapped())
    check(Language.fromCode("ja") == Language.JA && Language.fromCode("Japanese") == null)
    check(runCatching { LanguagePair(Language.JA, Language.JA) }.isFailure)
    val japanese = SourceGate(language = Language.JA)
    japanese.update("この薬は飲んではいけ", 0, 0)
    check(japanese.update("この薬は飲んではいけ", 1, 7000).committed == null)
    check(japanese.update("この薬は飲んではいけません", 2, 7500, true).committed == "この薬は飲んではいけません")
    val japanesePunctuation = SourceGate(language = Language.JA)
    japanesePunctuation.update("行きません。次の話です", 0, 0)
    check(japanesePunctuation.update("行きません。次の話です", 1, 500).committed == "行きません。")
    check(japanesePunctuation.update("行きません。次の話です", 2, 1000, true).committed == "次の話です")

    fun segment(sequence: Long, session: String = "one") =
        Segment(SegmentKey(session, sequence), "Source $sequence", sequence * 100, sequence * 100 + 50)

    val queue = TranslationQueue("one", capacity = 1, maxAgeMs = 1_000, contextCharacters = 20)
    check(queue.submit(segment(0)) == null)
    val first = checkNotNull(queue.take())
    check(queue.take() == null)
    check(queue.submit(segment(1)) == null)
    check(queue.submit(segment(2))?.untranslatedReason == UntranslatedReason.BACKLOG)
    check(queue.complete(first.segment.key.copy(sessionId = "old"), "old", 500) == null)
    check(queue.complete(first.segment.key.copy(revision = 1), "wrong", 500) == null)
    check(queue.complete(first.segment.key, "你好", 500)?.translation == "你好")
    check(queue.complete(first.segment.key, "duplicate", 500) == null)
    check(queue.take()?.context == listOf("Source 0"))
    check(queue.expire(1_150).single().untranslatedReason == UntranslatedReason.TIMED_OUT)
    check(queue.submit(segment(3)) == null)
    check(queue.take() == null) // Expiry must not overlap an unjoined native worker.
    check(queue.expire(1_160).isEmpty())
    check(queue.complete(segment(1).key, "late", 1_170) == null)
    check(queue.stop().single().untranslatedReason == UntranslatedReason.STOPPED)
    check(queue.complete(segment(3).key, "late", 1_200) == null)
    check(queue.submit(segment(4))?.untranslatedReason == UntranslatedReason.STOPPED)

    val stress = TranslationQueue("one", capacity = 3)
    val accounted = mutableSetOf<SegmentKey>()
    repeat(1_000) { i -> stress.submit(segment(i.toLong()))?.let { accounted += it.segment.key } }
    check(stress.pendingCount == 3)
    stress.stop().forEach { accounted += it.segment.key }
    check(accounted.size == 1_000)

    val contextQueue = TranslationQueue("one", contextCharacters = 4)
    contextQueue.submit(Segment(SegmentKey("one", 0), "Long source 😀", 0, 1))
    contextQueue.submit(segment(1))
    contextQueue.take()?.let { contextQueue.complete(it.segment.key, "ok", 100) }
    check(contextQueue.take()?.context?.isEmpty() == true)

    val correctionQueue = TranslationQueue("one")
    correctionQueue.submit(segment(0)); correctionQueue.take()
    correctionQueue.submit(segment(1))
    val retracted = correctionQueue.invalidate(setOf(segment(0).key))
    check(retracted.single().untranslatedReason == UntranslatedReason.SUPERSEDED)
    check(correctionQueue.take() == null)
    check(correctionQueue.complete(segment(0).key, "stale translation", 300) == null)
    check(correctionQueue.take()?.context?.isEmpty() == true)
    check(correctionQueue.stop().single().segment.key == segment(1).key)

    val scheduler = CaptionScheduler(capacity = 1, minDwellMs = 1_600)
    val a = Caption(segment(0), "第一句")
    val b = Caption(segment(1), "第二句")
    check(scheduler.offer(a))
    check(scheduler.tick(0)?.caption == a)
    check(scheduler.offer(b))
    check(!scheduler.offer(b))
    check(scheduler.tick(1_599)?.caption == a)
    check(scheduler.tick(1_600)?.caption == b)
    check(scheduler.tick(3_200) == null)
    check(!scheduler.offer(a))
    val paging = CaptionScheduler()
    check(paging.offer(a, listOf("One", "Two"), listOf("一", "二", "三")))
    check(paging.tick(0)?.index == 0)
    check(paging.tick(1_600)?.index == 1)
    check(paging.tick(3_200)?.index == 2)
    paging.invalidate(setOf(a.segment.key))
    check(paging.tick(3_300) == null)
    val reflow = CaptionScheduler()
    reflow.offer(a); reflow.tick(0); reflow.offer(b)
    reflow.reflow { text, _ -> text.map { it.toString() } }
    check(reflow.tick(10)?.total == a.segment.source.length)
    reflow.invalidate(setOf(a.segment.key))
    check(reflow.tick(20)?.caption == b)
    // Parallel languages must not make a readable page wait for both texts in sequence.
    val bilingual = CaptionScheduler()
    bilingual.offer(a, listOf("a".repeat(40)), listOf("中".repeat(20)))
    check(bilingual.tick(0)?.caption == a)
    bilingual.offer(b)
    check(bilingual.tick(1_999)?.caption == a)
    check(bilingual.tick(2_000)?.caption == b)
    // Mixed scripts, supplementary Han, and source-only outcomes use the same reading budget.
    val mixed = CaptionScheduler()
    mixed.offer(a, listOf("a".repeat(20) + "𠀀".repeat(20)), emptyList())
    check(mixed.tick(0)?.caption == a)
    mixed.offer(b)
    check(mixed.tick(2_999)?.caption == a)
    check(mixed.tick(3_000)?.caption == b)
    val kana = CaptionScheduler()
    kana.offer(a, listOf("あア한".repeat(10)), emptyList())
    check(kana.tick(0)?.caption == a)
    kana.offer(b)
    check(kana.tick(2_999)?.caption == a)
    check(kana.tick(3_000)?.caption == b)
    val capped = CaptionScheduler()
    capped.offer(a, listOf("中".repeat(100)), listOf("a".repeat(200)))
    check(capped.tick(0)?.caption == a)
    capped.offer(b)
    check(capped.tick(5_999)?.caption == a)
    check(capped.tick(6_000)?.caption == b)
    println("PASS: source/semantic gates, corrections, queue bounds, stale results, timeout, stop, completeness, reading dwell")
}
